### ISSUE TITLE
"Class '...\\App\\Zenaton\\Syncflow\\MyFirstWorkflow' not found",

### ISSUE THREAD

**Issue by lxon** [zenaton/zenaton-laravel#6]
Hi Pierre-Yves, 

This product/service looks promising, 
try follow as tutorial but hit: 
```
"message": "Class 'App\\Http\\Controllers\\App\\Zenaton\\MyFirstWorkflow' not found",
```

I try to dispatch from controller class by calling 
```
(new \App\Zenaton\Workflows\MyFirstWorkflow())->dispatch();
```

Anything I missing on the Laravel config?

**Comment by pylebecq** [comment]
Hi! 👋 

I think you're not missing anything on the Laravel config. This looks like a class namespace mismatch. 🤔 

Can you show me your workflow class? I'm mostly interested in the namespace of the class, and the class name itself.

Something weird is going on because if you dispatch from a controller using `(new \App\Zenaton\Workflows\MyFirstWorkflow())->dispatch();`, I would expect the message to be either `Class '\\App\\Zenaton\\Workflows\\MyFirstWorkflow' not found`.

**Comment by pylebecq** [comment]
I just tried right now to make sure everything works fine, and it did, using Laravel 5.8 and zenaton-laravel 0.1.1.

This is my workflow:

```php
<?php
// file app/Zenaton/Workflows/MyWorkflow.php

namespace App\Zenaton\Workflows;

use Zenaton\Interfaces\WorkflowInterface;
use Zenaton\Tasks\Wait;
use Zenaton\Traits\Zenatonable;

class MyWorkflow implements WorkflowInterface
{
    use Zenatonable;

    public function handle()
    {
        (new Wait())->seconds(32)->execute();
    }
}
```

And I dispatch it in a controller:

```php
<?php
// file app/Http/Controllers/MyController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MyController extends Controller
{
    public function index(Request $request)
    {
        (new \App\Zenaton\Workflows\MyWorkflow())->dispatch();

        return response()->json(['success' => true]);
    }
}
```

This executes just fine:

![image](https://user-images.githubusercontent.com/351471/66035394-58479d00-e50b-11e9-9e50-c8dcf6690940.png)

**Comment by lxon** [comment]
Hi, 

Appreciate and thanks for your prompt reply, 
😅 real sorry for my simple mistake on the `\App` under my own controller class: 
*accidentally remove `\`.
Incorrect: 
```
(new App\Zenaton\Workflows\MyFirstWorkflow())->dispatch();
```

Correct:
```
(new \App\Zenaton\Workflows\MyFirstWorkflow())->dispatch();
```

👏 Zenaton such an amazing product/service, 
looking forward to its implementation/development journey.

**Comment by pylebecq** [comment]
I see. I'm glad it works fine for you!
I'll close this issue then.

Thank you for your kind words.
If you need further support don't hesitate to open issues in case of bugs, or give some feedback/ask for help using the chat at the bottom right of the website or using the Zenaton Community slack.

**Comment by lxon** [comment]
Sure, will do. 👍
Nice day ahead.
